INSERT INTO add_country (country) VALUES ('Бразилия');
INSERT INTO add_country (country) VALUES ('Греция');
INSERT INTO add_country (country) VALUES ('Канада');


-- Brasil
INSERT INTO cat_airports (name, country) VALUES('Белен Вал Де Канс', 10);
INSERT INTO cat_airports (name, country) VALUES('Белу-Оризонти Пампула', 10);
INSERT INTO cat_airports (name, country) VALUES('Боа-Виста', 10);
INSERT INTO cat_airports (name, country) VALUES('Бразилиа Президент Жуселино Кубичек', 10);
INSERT INTO cat_airports (name, country) VALUES('Куритиба Афонсо Пена', 10);
INSERT INTO cat_airports (name, country) VALUES('Манаус Эдуардо Гомес', 10);
INSERT INTO cat_airports (name, country) VALUES('Патус-ди-Минас', 10);
INSERT INTO cat_airports (name, country) VALUES('Порту-Алегри Салгадо Фило', 10);
INSERT INTO cat_airports (name, country) VALUES('Ресифи Гуарарапес', 10);
INSERT INTO cat_airports (name, country) VALUES('Рибейран-Прету Лейте Лопес', 10);
INSERT INTO cat_airports (name, country) VALUES('Рио-де-Жанейро Галеан Том Жобим', 10);
INSERT INTO cat_airports (name, country) VALUES('Рио-де-Жанейро Сантос Дюмон', 10);
INSERT INTO cat_airports (name, country) VALUES('Сальвадор Луис Эдуардо Магальес', 10);
INSERT INTO cat_airports (name, country) VALUES('Сан-Паулу Гуарулхос', 10);
INSERT INTO cat_airports (name, country) VALUES('Сан-Паулу Конгоньяс', 10);
INSERT INTO cat_airports (name, country) VALUES('Сантарен Уилсон Фонсека', 10);
INSERT INTO cat_airports (name, country) VALUES('Форталеза Пинто Мартинс', 10);
INSERT INTO cat_airports (name, country) VALUES('Фос-ду-Игуасу Катаратас', 10);

-- Greece
INSERT INTO cat_airports (name, country) VALUES('Александруполис Демокрит', 11);
INSERT INTO cat_airports (name, country) VALUES('Афины Элефтериос Венизелос', 11);
INSERT INTO cat_airports (name, country) VALUES('Волос Неа Анхилаос', 11);
INSERT INTO cat_airports (name, country) VALUES('Закинтос Дионисий Соломос', 11);
INSERT INTO cat_airports (name, country) VALUES('Ираклион Никос Казантзакис', 11);
INSERT INTO cat_airports (name, country) VALUES('Кавала Мегас Александрос', 11);
INSERT INTO cat_airports (name, country) VALUES('Каламата Василис Константакопулос', 11);
INSERT INTO cat_airports (name, country) VALUES('Карпатос', 11);
INSERT INTO cat_airports (name, country) VALUES('Керкира Корфу Иоанис Каподистриас', 11);
INSERT INTO cat_airports (name, country) VALUES('Кефалония', 11);
INSERT INTO cat_airports (name, country) VALUES('Китира', 11);
INSERT INTO cat_airports (name, country) VALUES('Кос Гиппократ', 11);
INSERT INTO cat_airports (name, country) VALUES('Лемнос', 11);
INSERT INTO cat_airports (name, country) VALUES('Миконос', 11);
INSERT INTO cat_airports (name, country) VALUES('Милос', 11);
INSERT INTO cat_airports (name, country) VALUES('Митилини', 11);
INSERT INTO cat_airports (name, country) VALUES('Наксос', 11);
INSERT INTO cat_airports (name, country) VALUES('Парос', 11);
INSERT INTO cat_airports (name, country) VALUES('Патры Араксос', 11);
INSERT INTO cat_airports (name, country) VALUES('Превеза Актион', 11);
INSERT INTO cat_airports (name, country) VALUES('Родос Диагорас', 11);
INSERT INTO cat_airports (name, country) VALUES('Салоники Македония', 11);
INSERT INTO cat_airports (name, country) VALUES('Санторини', 11);
INSERT INTO cat_airports (name, country) VALUES('Скиатос', 11);
INSERT INTO cat_airports (name, country) VALUES('Ханья Даскалогианис', 11);
INSERT INTO cat_airports (name, country) VALUES('Хиос', 11);
INSERT INTO cat_airports (name, country) VALUES('Янина Кинг Пиррос', 11);

-- Canada
INSERT INTO cat_airports (name, country) VALUES('Баие-Комо', 12);
INSERT INTO cat_airports (name, country) VALUES('Белла-Кула', 12);
INSERT INTO cat_airports (name, country) VALUES('Ванкувер', 12);
INSERT INTO cat_airports (name, country) VALUES('Ванкувер Баундари-Бей', 12);
INSERT INTO cat_airports (name, country) VALUES('Ванкувер Харбор Уотер', 12);
INSERT INTO cat_airports (name, country) VALUES('Виктория', 12);
INSERT INTO cat_airports (name, country) VALUES('Виннипег Джеймс Армстронг Ричардсон', 12);
INSERT INTO cat_airports (name, country) VALUES('Галифакс Стэнфилд', 12);
INSERT INTO cat_airports (name, country) VALUES('Гамильтон Джон Манро', 12);
INSERT INTO cat_airports (name, country) VALUES('Гранд-Прери', 12);
INSERT INTO cat_airports (name, country) VALUES('Икалуит', 12);
INSERT INTO cat_airports (name, country) VALUES('Инувик Майк Зубко', 12);
INSERT INTO cat_airports (name, country) VALUES('Йеллоунайф', 12);
INSERT INTO cat_airports (name, country) VALUES('Калгари', 12);
INSERT INTO cat_airports (name, country) VALUES('Квебек Жан Лесаж', 12);
INSERT INTO cat_airports (name, country) VALUES('Келоуна', 12);
INSERT INTO cat_airports (name, country) VALUES('Крэнбрук Канадиан Рокиз', 12);
INSERT INTO cat_airports (name, country) VALUES('Кэмпбелл Ривер', 12);
INSERT INTO cat_airports (name, country) VALUES('Ла Ронж', 12);
INSERT INTO cat_airports (name, country) VALUES('Медисин-Хат', 12);
INSERT INTO cat_airports (name, country) VALUES('Монреаль Мирабель', 12);
INSERT INTO cat_airports (name, country) VALUES('Монреаль Пьер Трюдо', 12);
INSERT INTO cat_airports (name, country) VALUES('Накина', 12);
INSERT INTO cat_airports (name, country) VALUES('Норман-Уэлс', 12);
INSERT INTO cat_airports (name, country) VALUES('Норт-Бей Джек Гарланд', 12);
INSERT INTO cat_airports (name, country) VALUES('Оттава Макдоналд-Картье', 12);
INSERT INTO cat_airports (name, country) VALUES('Пикл-Лейк', 12);
INSERT INTO cat_airports (name, country) VALUES('Повелл Ривер', 12);
INSERT INTO cat_airports (name, country) VALUES('Порт-Алберни', 12);
INSERT INTO cat_airports (name, country) VALUES('Порт-Харди', 12);
INSERT INTO cat_airports (name, country) VALUES('Принс-Альберт', 12);
INSERT INTO cat_airports (name, country) VALUES('Принс-Джордж', 12);
INSERT INTO cat_airports (name, country) VALUES('Ранкин-Инлет', 12);
INSERT INTO cat_airports (name, country) VALUES('Ред-Лейк', 12);
INSERT INTO cat_airports (name, country) VALUES('Реджайна', 12);
INSERT INTO cat_airports (name, country) VALUES('Репалс-Бей', 12);
INSERT INTO cat_airports (name, country) VALUES('Садбери', 12);
INSERT INTO cat_airports (name, country) VALUES('Саскатун Джон Дифенбакер', 12);
INSERT INTO cat_airports (name, country) VALUES('Сент-Джонс', 12);
INSERT INTO cat_airports (name, country) VALUES('Сет-Иль', 12);
INSERT INTO cat_airports (name, country) VALUES('Смитерс', 12);
INSERT INTO cat_airports (name, country) VALUES('Су Лукаут', 12);
INSERT INTO cat_airports (name, country) VALUES('Тандер-Бей', 12);
INSERT INTO cat_airports (name, country) VALUES('Террас', 12);
INSERT INTO cat_airports (name, country) VALUES('Тимминс Виктор Пауэр', 12);
INSERT INTO cat_airports (name, country) VALUES('Томпсон', 12);
INSERT INTO cat_airports (name, country) VALUES('Торонто Пирсон', 12);
INSERT INTO cat_airports (name, country) VALUES('Торонто Сити Билли Бишоп', 12);
INSERT INTO cat_airports (name, country) VALUES('Тофино', 12);
INSERT INTO cat_airports (name, country) VALUES('Уайтхорс Эрик Нильсен', 12);
INSERT INTO cat_airports (name, country) VALUES('Уильямс-Лейк', 12);
INSERT INTO cat_airports (name, country) VALUES('Форт-Макмюррей', 12);
INSERT INTO cat_airports (name, country) VALUES('Форт-Сент-Джон', 12);
INSERT INTO cat_airports (name, country) VALUES('Форт-Смит', 12);
INSERT INTO cat_airports (name, country) VALUES('Черчилль', 12);
INSERT INTO cat_airports (name, country) VALUES('Эдмонтон', 12);
INSERT INTO cat_airports (name, country) VALUES('Эдмонтон Сити Центр', 12);
